<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <ProjectReference Include="../../../src/PSWSMan.Lib/PSWSMan.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../data/WinRSCommandLine.json" Link="WinRSCommandLine.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
