<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <!--MonoMod.Utils already exposes IgnoresAccessChecksToAttribute publicly-->
    <IgnoresAccessChecksToOmitAttributeDefinition>true</IgnoresAccessChecksToOmitAttributeDefinition>
  </PropertyGroup>

  <ItemGroup>
    <IgnoresAccessChecksTo Include="System.Management.Automation" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Devolutions.Sspi" />
    <PackageReference Include="MonoMod.RuntimeDetour" />
    <ProjectReference Include="../PSWSMan.Loader/PSWSMan.Loader.csproj" />
    <PackageReference Include="IgnoresAccessChecksToGenerator" PrivateAssets="All" />
    <PackageReference Include="System.Formats.Asn1" PrivateAssets="all" />
    <Reference Include="../../output/System.Management.Automation/$(TargetFramework)/System.Management.Automation.dll" Private="false" />
  </ItemGroup>
</Project>
